development:
  adapter: postgresql
  encoding: utf8
  database: mimimama
  pool: 5
  username: pgsql
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: mimimama_test
  pool: 5
  username: mimimama
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mimimama_production
  pool: 5
  username: mimimama
  password:
